version: "3"
services:
  elasticsearch:
    image: "guillermoleiva/elasticsearchimdb:test"
    hostname: "elasticsearch"
    container_name: elasticsearch-docker
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=https://app.elasticvue.com, http://cerebro:9000
    ports:
      - 9200:9200
  cerebro:
    image: lmenezes/cerebro
    ports:
      - 9000:9000
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
  springbootapp:
    container_name: springbootapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      - elasticsearch